### ISSUE TITLE
Guide for syncing custom data

### ISSUE THREAD

**Issue by chylex** [DeckHack/discoveries#4]
---

<p align="center"><i>Message edited by @pixeldesu</i><br/> 
<b>Messing with this feature might lead to trouble with TweetDeck, so we better leave it be</b></p>

---

**Comment by EntranceJew** [comment]
@chylex this is pretty cool! I have no idea what's actually happening in that last example other than it presumably cycles the keys in some way.

Is there a closer relation between those functions and the trigger `dataSettingsValues` getting activated?

**Comment by chylex** [comment]
I suspect the sync is happening in dictSet, which is not really useful since you need to give it a key/value pair anyways and reimplementing the code (dirtying cache, pushing notify event, pushing sync) is too much of a hassle.

**Comment by chylex** [comment]
We do not have blessing from TweetDeck devs to use this, the guys who manage the storage would get pissy :P
